server:
  port: 8080
  mode: debug # debug, release, test
  read_timeout: 60
  write_timeout: 60
  base_url: "https://frp.qinyibaby.cn" # 小程序码和其他资源的完整访问 URL

database:
  host: 101.200.47.93
  port: 5432
  user: postgres
  password: 3f2z5C2zwaPDsmLG
  dbname: test
  sslmode: disable
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600

redis:
  host: 101.200.47.93
  port: 26379
  password: "3pzhbpe4"
  db: 0
  pool_size: 10

jwt:
  secret: your-secret-key-change-in-production
  expire_hours: 72

log:
  level: debug # debug, info, warn, error
  filename: logs/app.log
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
  compress: true

upload:
  max_size: 10485760 # 10MB
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
  storage_path: uploads/

wechat:
  app_id: wxf47340979046b474
  app_secret: c5b5f88848865bc3b0ac9ba5aa1f477e
  # 订阅消息模板ID配置
  subscribe_templates:
    # 喂养提醒模板
    breast_feeding_reminder: "2JRV0DnOHnasHzzamWFoWGaUxrgW6GY69-eGn4tBFZE"   # 母乳喂养提醒
    bottle_feeding_reminder: "ssttSBSWM_IXh5zVOu9GBeuabX8NFcwM2IG-VK-RXNY"   # 奶瓶喂养提醒
    food_feeding_reminder: "ssttSBSWM_IXh5zVOu9GBeuabX8NFcwM2IG-VK-RXNY"     # 辅食喂养提醒
    # 疫苗提醒模板
    vaccine_reminder: "YOUR_VACCINE_REMINDER_TEMPLATE_ID"
